services:
  mongo.db.catalog:
    restart: always
    image: mongo:8.0-rc
    container_name: mongo.db.catalog.container
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
        - "27030:27017"
    volumes:
        - mongo.db.catalog.volume:/data/db
  mongo.db.catalog.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.catalog.ui.container
    ports:
    - 27032:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.catalog:27017/
      ME_CONFIG_BASICAUTH: false
  redis.db.basket:
    restart: always
    image: redis:7.0-alpine
    container_name: redis.db.container
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
        - "6379:6379"
    volumes:
        - "redis.db.basket.volume:/data" 
  redis.db.ui:
    restart: always
    image: rediscommander/redis-commander:latest
    container_name: redis.db.basket.ui.container
    ports:
        - "27033:8081"
    environment:
        REDIS_HOST: redis.db.basket
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        HTTP_USER: ${REDIS_UI_USERNAME}
        HTTP_PASSWORD: ${REDIS_UI_PASSWORD}

    
volumes:
    mongo.db.catalog.volume:
    redis.db.basket.volume: